backend:
  name: git-gateway
  branch: main

media_folder: "assets/upload"  # Allineato alla tua struttura
public_folder: "/assets/upload"  # Allineato alla tua struttura

media_library:  # Aggiungi questa sezione
  name: uploadcare
  config:
    publicKey: "demopublickey"

collections:
  - name: "prezzi"  # Nome cambiato da 'pricing'
    label: "Pacchetti"
    folder: "content/prezzi"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nome", name: "name", widget: "string" }
      - { label: "Prezzo", name: "price", widget: "string" }
      - { label: "Descrizione", name: "description", widget: "text" }

  - name: "servizi"  # Nome cambiato da 'portfolio'
    label: "Servizi"
    folder: "content/servizi"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titolo", name: "title", widget: "string" }
      - { label: "Descrizione", name: "description", widget: "text" }
      - { label: "Icona", name: "icon", widget: "image" }

  - name: "testimonianze"  # Nome cambiato da 'testimonials'
    label: "Testimonianze"
    folder: "content/testimonianze"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nome", name: "name", widget: "string" }
      - { label: "Ruolo", name: "role", widget: "string" }
      - { label: "Testimonianza", name: "quote", widget: "text" }

  - name: "hero"
    label: "Hero Section"
    file: "content/hero.md"
    fields:
      - { label: "Titolo", name: "title", widget: "string" }
      - { label: "Sottotitolo", name: "subtitle", widget: "text" }
