backend:
  name: git-gateway
  branch: main

media_folder: "admin/assets/uploads"  # Modificato
public_folder: "/admin/assets/uploads"  # Modificato

collections:
  - name: "hero"
    label: "Sezione Hero"
    files:
      - file: "admin/content/hero.md"  # Percorso completo
        label: "Contenuto Hero"
        name: "hero"
        fields:
          - { label: "Titolo", name: "title", widget: "string" }
          - { label: "Sottotitolo", name: "subtitle", widget: "string" }

  - name: "prezzi"  # Rinominato da pricing
    label: "Pacchetti e Prezzi"
    folder: "admin/content/prezzi"  # Percorso completo
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nome Pacchetto", name: "name", widget: "string" }
      - { label: "Prezzo", name: "price", widget: "string" }
      - { label: "Descrizione", name: "description", widget: "text" }

  - name: "servizi"  # Rinominato da portfolio
    label: "Servizi"
    folder: "admin/content/servizi"  # Percorso completo
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titolo Servizio", name: "title", widget: "string" }
      - { label: "Descrizione", name: "description", widget: "text" }
      - { label: "Immagine", name: "image", widget: "image" }

  - name: "testimonianze"  # Rinominato da testimonials
    label: "Testimonianze"
    folder: "admin/content/testimonianze"  # Percorso completo
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nome", name: "name", widget: "string" }
      - { label: "Ruolo", name: "role", widget: "string" }
      - { label: "Testimonianza", name: "quote", widget: "text" }
      - { label: "Avatar", name: "avatar", widget: "image" }

  # Rimuovi o aggiusta le sezioni non esistenti (faq, popup)
