backend:
  name: github
  repo: demasiadowear/boostami-site
  branch: main
  auth_type: implicit
  site_url: https://boostami.online
  base_url: https://api.github.com

# Aggiungi queste sezioni OBBLIGATORIE
media_folder: "static/uploads"  # Cartella dove salvare i media
public_folder: "/uploads"       # Percorso pubblico per i media
media_library:                  # Configurazione libreria media
  name: uploadcare
  config:
    publicKey: demopublickey

collections:
  - name: "pages"
    label: "Pages"
    label_singular: "Page"
    folder: "content/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

# Configurazione minima funzionante
display_url: https://boostami.online
locale: "it"
