backend:
  name: github
  repo: demasiadowear/boostami-site
  branch: main
  auth_type: implicit
  base_url: https://api.github.com
  site_url: https://boostami.online
  commit_messages:
    create: "Create {{collection}} '{{slug}}'"
    update: "Update {{collection}} '{{slug}}'"
    delete: "Delete {{collection}} '{{slug}}'"
    uploadMedia: "Upload '{{path}}'"
    deleteMedia: "Delete '{{path}}'"

publish_mode: editorial_workflow
media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "pages"
    label: "Pagine"
    files:
      - file: "content/pages/home.md"
        label: "Homepage"
        name: "homepage"
        fields:
          - {label: "Titolo", name: "title", widget: "string"}
          - {label: "Contenuto", name: "body", widget: "markdown"}
