# Configurazione minima per testare
backend:
  name: test-repo

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "test"
    label: "Test"
    folder: "content/test"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
