backend:
  name: git-gateway
  branch: main

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "settings"
    label: "Impostazioni Sito"
    files:
      - label: "Configurazione Generale"
        name: "general"
        file: "data/settings.json"
        fields:
          - {label: "Titolo Sito", name: "site_title", widget: "string", default: "Boostami"}
          - {label: "Descrizione Sito", name: "site_description", widget: "text", default: "Brand Kit Professionali in 48h"}
          - {label: "URL Sito", name: "site_url", widget: "string", default: "https://boostami.online"}
          - {label: "Email Contatto", name: "contact_email", widget: "string", default: "info@boostami.online"}
          - {label: "Telefono", name: "phone", widget: "string", required: false}

  - name: "hero"
    label: "Sezione Hero"
    files:
      - label: "Hero Homepage"
        name: "hero_home"
        file: "content/hero.md"
        fields:
          - {label: "Titolo Principale", name: "title", widget: "string", default: "Il Tuo Brand Professionale in 48 Ore"}
          - {label: "Sottotitolo", name: "subtitle", widget: "text", default: "Servizio digitale chiavi in mano per piccole attività locali, freelance e microimprese. Logo, palette, template social e mini-sito pronti all'uso."}
          - {label: "Testo Pulsante Principale", name: "cta_text", widget: "string", default: "Crea il Tuo Brand Kit"}
          - {label: "Link Pulsante Principale", name: "cta_link", widget: "string", default: "#form"}
          - {label: "Immagine Hero", name: "hero_image", widget: "image", required: false}
          - {label: "Video Background", name: "video_bg", widget: "string", required: false}

  - name: "features"
    label: "Caratteristiche"
    files:
      - label: "Cosa Include il Brand Kit"
        name: "features"
        file: "content/features.md"
        fields:
          - {label: "Titolo Sezione", name: "section_title", widget: "string", default: "Cosa Include il Tuo Brand Kit"}
          - {label: "Descrizione Sezione", name: "section_description", widget: "text", default: "Tutto quello che serve per un brand professionale"}
          - label: "Lista Caratteristiche"
            name: "features_list"
            widget: "list"
            fields:
              - {label: "Icona", name: "icon", widget: "string"}
              - {label: "Titolo", name: "title", widget: "string"}
              - {label: "Descrizione", name: "description", widget: "text"}

  - name: "pricing"
    label: "Prezzi"
    files:
      - label: "Pacchetti e Prezzi"
        name: "pricing"
        file: "content/pricing.md"
        fields:
          - {label: "Titolo Sezione", name: "section_title", widget: "string", default: "Scegli il Tuo Pacchetto"}
          - {label: "Descrizione Sezione", name: "section_description", widget: "text", default: "Prezzi trasparenti, nessun costo nascosto"}
          - label: "Pacchetti"
            name: "packages"
            widget: "list"
            fields:
              - {label: "Nome Pacchetto", name: "name", widget: "string"}
              - {label: "Prezzo", name: "price", widget: "number"}
              - {label: "Valuta", name: "currency", widget: "string", default: "€"}
              - {label: "Descrizione", name: "description", widget: "text"}
              - {label: "Più Popolare", name: "popular", widget: "boolean", default: false}
              - label: "Caratteristiche"
                name: "features"
                widget: "list"
                field: {label: "Caratteristica", name: "feature", widget: "string"}
              - {label: "Testo Pulsante", name: "button_text", widget: "string", default: "Scegli"}
              - {label: "Link Pulsante", name: "button_link", widget: "string"}

  - name: "testimonials"
    label: "Testimonianze"
    folder: "content/testimonials"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Nome Cliente", name: "name", widget: "string"}
      - {label: "Azienda", name: "company", widget: "string"}
      - {label: "Testimonianza", name: "testimonial", widget: "text"}
      - {label: "Rating", name: "rating", widget: "number", min: 1, max: 5, default: 5}
      - {label: "Foto Cliente", name: "photo", widget: "image", required: false}
      - {label: "Data", name: "date", widget: "datetime"}

  - name: "pages"
    label: "Pagine"
    files:
      - label: "Chi Siamo"
        name: "about"
        file: "content/about.md"
        fields:
          - {label: "Titolo", name: "title", widget: "string", default: "Chi Siamo"}
          - {label: "Contenuto", name: "body", widget: "markdown"}
          - {label: "Immagine", name: "image", widget: "image", required: false}
      
      - label: "Contatti"
        name: "contact"
        file: "content/contact.md"
        fields:
          - {label: "Titolo", name: "title", widget: "string", default: "Contatti"}
          - {label: "Descrizione", name: "description", widget: "text"}
          - {label: "Email", name: "email", widget: "string"}
          - {label: "Telefono", name: "phone", widget: "string", required: false}
          - {label: "Indirizzo", name: "address", widget: "text", required: false}
          - {label: "Orari", name: "hours", widget: "text", required: false}

  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Titolo", name: "title", widget: "string"}
      - {label: "Data", name: "date", widget: "datetime"}
      - {label: "Autore", name: "author", widget: "string", default: "Boostami Team"}
      - {label: "Descrizione", name: "description", widget: "text"}
      - {label: "Immagine", name: "image", widget: "image", required: false}
      - {label: "Tag", name: "tags", widget: "list", required: false}
      - {label: "Contenuto", name: "body", widget: "markdown"}

